"""Self-development builder — completes the prepare-only pipeline.

The existing ``openjarvis.self_development.pipeline`` intentionally stops
at "prepared" (plan + docs snapshot, activation blocked). This module
completes the loop so Jarvis can actually extend itself:

    plan → GENERATE → VALIDATE → ACTIVATE → (rollback on failure)

* ``generate``   — write a full tool module from a spec (name, description,
  parameters schema, implementation code).
* ``validate``   — compile check, forbidden-pattern scan, subprocess import
  test with timeout, spec sanity, dry-call smoke test.
* ``activate``   — install under ``~/.openjarvis/self-dev/tools/``, keep a
  baseline copy for recovery, register into ToolRegistry, and inject into
  the running agent executors.
* ``rollback``   — quarantine the broken module and restore the baseline
  (via ``recovery.watchdog.RecoveryCore``).

Nothing in the production source tree is ever modified — self-developed
tools live in the config directory and are loaded dynamically.
"""

from __future__ import annotations

import importlib.util
import logging
import re
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from openjarvis.core.registry import ToolRegistry
from openjarvis.core.types import ToolResult
from openjarvis.tools._stubs import BaseTool, ToolSpec

logger = logging.getLogger(__name__)

_LOCK = threading.RLock()

_SAFE_NAME = re.compile(r"^[a-z][a-z0-9_]{2,40}$")

# Basic safety scan for obviously dangerous constructs in generated code.
_FORBIDDEN_PATTERNS = [
    (r"rm\s+-rf", "destructive shell command"),
    (r"shutil\.rmtree\(\s*[\"'`\s]*[\"'`]?\s*/", "deleting root paths"),
    (r"os\.system\s*\(", "raw os.system call"),
    (r"subprocess\.(run|call|Popen)\(\s*[\"'][^\"']*(?:rm|del|format|mkfs)",
     "destructive subprocess"),
    (r"eval\s*\(\s*(?:input|request|open)", "eval of untrusted input"),
    (r"__import__\s*\(\s*[\"']sys[\"']\s*\)\.exit", "hard interpreter exit"),
    (r"open\(\s*[\"'][~/]{1}[^\"']*[\"']\s*,\s*[\"']w", "writing outside workspace"),
]

_MAX_CODE_BYTES = 200_000

_TOOL_TEMPLATE = '''"""Self-developed tool "{name}" — generated by Jarvis self-dev builder.

Generated: {timestamp}
Request: {request}
"""

from __future__ import annotations

import logging
from typing import Any

from openjarvis.core.registry import ToolRegistry
from openjarvis.core.types import ToolResult
from openjarvis.tools._stubs import BaseTool, ToolSpec

logger = logging.getLogger(__name__)


@ToolRegistry.register("{name}")
class {cls_name}(BaseTool):
    """{doc}"""

    tool_id = "{name}"
    is_local = {is_local}

    @property
    def spec(self) -> ToolSpec:
        return ToolSpec(
            name="{name}",
            description={description!r},
            parameters={parameters!r},
            category="{category}",
            timeout_seconds={timeout},
        )

{implementation}
'''


def _self_dev_root() -> Path:
    from openjarvis.core.paths import get_config_dir

    root = get_config_dir() / "self-dev"
    (root / "tools").mkdir(parents=True, exist_ok=True)
    (root / "baseline").mkdir(parents=True, exist_ok=True)
    return root


def _tools_dir() -> Path:
    return _self_dev_root() / "tools"


def _baseline_dir() -> Path:
    return _self_dev_root() / "baseline"


def validate_code(code: str) -> List[str]:
    """Return a list of validation errors (empty = valid)."""
    errors: List[str] = []
    if not code or not code.strip():
        return ["empty code"]
    if len(code.encode("utf-8")) > _MAX_CODE_BYTES:
        errors.append(f"code exceeds {_MAX_CODE_BYTES} bytes")
    try:
        compile(code, "<generated-tool>", "exec")
    except SyntaxError as exc:
        errors.append(f"syntax error: {exc}")
        return errors
    for pattern, reason in _FORBIDDEN_PATTERNS:
        if re.search(pattern, code):
            errors.append(f"forbidden pattern ({reason})")
    if "BaseTool" not in code:
        errors.append("implementation must define a BaseTool subclass")
    if "def execute" not in code:
        errors.append("implementation must define execute()")
    return errors


def generate_module(
    name: str,
    *,
    description: str,
    parameters: Dict[str, Any],
    implementation: str,
    request: str = "",
    category: str = "self-dev",
    timeout: float = 60.0,
    is_local: bool = True,
) -> str:
    """Render the complete tool module source from a spec."""
    if not _SAFE_NAME.fullmatch(name or ""):
        raise ValueError(f"invalid tool name '{name}' (a-z, 0-9, _)")
    cls_name = "".join(part.capitalize() for part in name.split("_")) + "Tool"
    impl = implementation.strip("\n")
    if not impl.startswith(("class ", "@", "    def ", "    @")):
        # Caller passed a method body (def execute…) — indent into the class.
        impl = "\n".join(("    " + line) if line.strip() else line
                         for line in impl.split("\n"))
    return _TOOL_TEMPLATE.format(
        name=name, cls_name=cls_name, doc=description.replace('"', "'")[:100],
        description=description, parameters=parameters, request=request[:200],
        category=category, timeout=timeout, is_local=is_local,
        implementation=impl or "    def execute(self, **params: Any) -> ToolResult:\n"
                              "        return ToolResult(tool_name='self_dev_build',\n"
                              "                          content='not implemented', success=False)",
        timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
    )


def _import_in_subprocess(module_path: Path, name: str, timeout: float = 25.0) -> List[str]:
    """Import the module in a clean interpreter with a hard timeout."""
    code = (
        "import importlib.util, sys\n"
        f"spec = importlib.util.spec_from_file_location({name!r}, {str(module_path)!r})\n"
        f"module = importlib.util.module_from_spec(spec)\n"
        "sys.modules['openjarvis_selfdev_probe'] = module\n"
        "spec.loader.exec_module(module)\n"
        "print('IMPORT_OK')\n"
    )
    # Make the openjarvis package importable in the child even when the
    # server runs from a source checkout (not pip-installed).
    import os

    import openjarvis

    pkg_parent = str(Path(openjarvis.__file__).resolve().parent.parent)
    env = dict(os.environ)
    env["PYTHONPATH"] = pkg_parent + os.pathsep + env.get("PYTHONPATH", "")
    try:
        proc = subprocess.run(
            [sys.executable, "-c", code],
            capture_output=True, text=True, timeout=timeout,
            cwd=str(_self_dev_root().parent), env=env,
        )
    except subprocess.TimeoutExpired:
        return [f"import timed out after {timeout:.0f}s"]
    if proc.returncode != 0 or "IMPORT_OK" not in (proc.stdout or ""):
        return [f"import failed: {(proc.stderr or proc.stdout or '')[-600:]}"]
    return []


def activate_tool(name: str, module_source: str) -> Dict[str, Any]:
    """Validate, install, baseline, register and inject a new tool.

    Returns a dict with ``status`` and details; on any failure the module
    is quarantined and the previous baseline (if any) is restored.
    """
    errors = validate_code(module_source)
    if errors:
        return {"status": "invalid", "errors": errors}

    with _LOCK:
        module_path = _tools_dir() / f"{name}.py"
        existed = module_path.exists()
        # Write the module.
        tmp = module_path.with_suffix(".py.tmp")
        tmp.write_text(module_source, "utf-8")
        tmp.replace(module_path)

        # Validate in a clean subprocess.
        errs = _import_in_subprocess(module_path, f"selfdev_{name}")
        if errs:
            _quarantine(name)
            return {"status": "validation_failed", "errors": errs,
                    "rolled_back": existed}

        # In-process load + register (drop any previous registration
        # first — ToolRegistry.register raises on duplicate keys).
        try:
            try:
                ToolRegistry._entries().pop(name, None)
            except Exception:
                pass
            spec = importlib.util.spec_from_file_location(
                f"openjarvis_selfdev_{name}", module_path
            )
            module = importlib.util.module_from_spec(spec)
            sys.modules[spec.name] = module
            spec.loader.exec_module(module)
            tool_cls = next(
                obj for obj in vars(module).values()
                if isinstance(obj, type) and issubclass(obj, BaseTool)
                and obj is not BaseTool
            )
            if not ToolRegistry.contains(name):
                ToolRegistry.register(name)(tool_cls)
            instance = tool_cls()
            smoke = instance.execute()
            if not isinstance(smoke, ToolResult):
                raise TypeError("execute() must return ToolResult")
        except Exception as exc:
            _quarantine(name)
            return {"status": "activation_failed", "errors": [str(exc)],
                    "rolled_back": existed}

        # Baseline for future recovery.
        baseline = _baseline_dir() / f"{name}.py"
        baseline.write_text(module_source, "utf-8")

        # Inject into running agents (executor dictionaries are read per turn).
        injected = inject_into_running_agents(instance)

        return {
            "status": "activated",
            "tool": name,
            "module": str(module_path),
            "baseline": str(baseline),
            "injected_into_agents": injected,
        }


def inject_into_running_agents(tool: BaseTool) -> List[str]:
    """Add a live tool instance to every running agent executor."""
    from openjarvis.creative.runtime import running_agents

    injected: List[str] = []
    for agent_id, agent in list(running_agents().items()):
        try:
            executor = getattr(agent, "_executor", None)
            if executor is not None and hasattr(executor, "_tools"):
                executor._tools[tool.spec.name] = tool
            tools_list = getattr(agent, "_tools", None)
            if isinstance(tools_list, list):
                tools_list[:] = [t for t in tools_list
                                 if getattr(t, "spec", None) is None
                                 or t.spec.name != tool.spec.name]
                tools_list.append(tool)
            injected.append(agent_id)
        except Exception as exc:
            logger.debug("inject into %s failed: %s", agent_id, exc)
    return injected


def _quarantine(name: str) -> None:
    module_path = _tools_dir() / f"{name}.py"
    if module_path.exists():
        broken = module_path.with_suffix(".py.broken")
        broken.write_text(module_path.read_text("utf-8"), "utf-8")
        module_path.unlink(missing_ok=True)
    # Restore the baseline if there was a previous good version.
    baseline = _baseline_dir() / f"{name}.py"
    if baseline.exists():
        (module_path).write_text(baseline.read_text("utf-8"), "utf-8")


def list_self_dev_tools() -> List[Dict[str, str]]:
    out = []
    for path in sorted(_tools_dir().glob("*.py")):
        out.append({"tool": path.stem, "module": str(path)})
    return out


def remove_tool(name: str) -> bool:
    with _LOCK:
        module_path = _tools_dir() / f"{name}.py"
        baseline = _baseline_dir() / f"{name}.py"
        removed = module_path.exists()
        module_path.unlink(missing_ok=True)
        baseline.unlink(missing_ok=True)
        return removed


@ToolRegistry.register("self_dev_build")
class SelfDevBuildTool(BaseTool):
    """Let Jarvis write and integrate new tools for itself, safely."""

    tool_id = "self_dev_build"
    is_local = True

    @property
    def spec(self) -> ToolSpec:
        return ToolSpec(
            name="self_dev_build",
            description=(
                "Extend Jarvis with a NEW tool written by Jarvis itself."
                " Pipeline: generate → validate (syntax scan, forbidden"
                " pattern scan, isolated import test, smoke call) →"
                " activate (registered in ToolRegistry + injected into"
                " running agents) — with automatic rollback to the last"
                " known-good baseline on any failure. Self-developed tools"
                " live in ~/.openjarvis/self-dev/tools (the production"
                " source tree is never touched). Actions: build (provide"
                " name, description, parameters JSON schema and the"
                " execute() implementation), validate (check code without"
                " activating), list (installed self-dev tools), remove."
            ),
            parameters={
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "enum": ["build", "validate", "list", "remove"],
                        "default": "build",
                    },
                    "name": {
                        "type": "string",
                        "description": "Tool name (snake_case, a-z0-9_).",
                    },
                    "description": {
                        "type": "string",
                        "description": "Tool description shown to the agent.",
                    },
                    "parameters": {
                        "type": "object",
                        "description": "JSON schema of the tool parameters.",
                    },
                    "implementation": {
                        "type": "string",
                        "description": (
                            "The execute() method body (Python), or a full"
                            " class definition. Must return ToolResult."
                        ),
                    },
                    "request": {"type": "string",
                                "description": "Why this tool is being built."},
                    "category": {"type": "string", "default": "self-dev"},
                    "timeout_seconds": {"type": "number", "default": 60},
                },
                "required": ["action"],
            },
            category="self-development",
            timeout_seconds=120.0,
        )

    def execute(self, **params: Any) -> ToolResult:
        action = str(params.get("action") or "build").lower()
        if action == "list":
            tools = list_self_dev_tools()
            if not tools:
                return ToolResult(tool_name="self_dev_build",
                                  content="No self-developed tools installed yet.",
                                  success=True)
            return ToolResult(tool_name="self_dev_build",
                              content="\n".join(
                                  f"- {t['tool']} → {t['module']}" for t in tools),
                              success=True)
        if action == "remove":
            name = str(params.get("name") or "")
            if remove_tool(name):
                return ToolResult(tool_name="self_dev_build",
                                  content=f"Removed self-dev tool '{name}'.",
                                  success=True)
            return ToolResult(tool_name="self_dev_build",
                              content=f"No tool '{name}' to remove.", success=False)

        name = str(params.get("name") or "").strip()
        description = str(params.get("description") or "").strip()
        parameters = params.get("parameters") or {
            "type": "object", "properties": {}, "required": []
        }
        implementation = str(params.get("implementation") or "")

        if not name or not description:
            return ToolResult(tool_name="self_dev_build",
                              content="'name' and 'description' are required.",
                              success=False)
        try:
            source = generate_module(
                name, description=description,
                parameters=parameters if isinstance(parameters, dict) else {},
                implementation=implementation,
                request=str(params.get("request") or ""),
                category=str(params.get("category") or "self-dev"),
                timeout=float(params.get("timeout_seconds") or 60),
            )
        except ValueError as exc:
            return ToolResult(tool_name="self_dev_build", content=str(exc),
                              success=False)

        if action == "validate":
            errors = validate_code(source)
            if errors:
                return ToolResult(tool_name="self_dev_build",
                                  content="INVALID:\n- " + "\n- ".join(errors),
                                  success=False)
            return ToolResult(tool_name="self_dev_build",
                              content="VALID — ready to build. Call with"
                                      " action=build to activate.",
                              success=True)

        # action == "build"
        result = activate_tool(name, source)
        if result["status"] != "activated":
            return ToolResult(
                tool_name="self_dev_build",
                content=f"Build failed ({result['status']}):\n- "
                        + "\n- ".join(result.get("errors", []))
                        + ("\nRolled back to the last good version."
                           if result.get("rolled_back") else ""),
                success=False,
            )
        content = (
            f"Tool '{name}' is live.\n"
            f"- Module: {result['module']}\n"
            f"- Baseline kept: {result['baseline']}\n"
            f"- Registered in ToolRegistry and injected into "
            f"{len(result['injected_into_agents'])} running agent(s).\n"
            "Call it now by name — it appears in the next agent turn."
        )
        return ToolResult(tool_name="self_dev_build", content=content,
                          success=True)


__all__ = [
    "SelfDevBuildTool",
    "generate_module",
    "validate_code",
    "activate_tool",
    "list_self_dev_tools",
    "inject_into_running_agents",
]
